### ISSUE TITLE
Reduction of memory requirements to run benchmarks

### ISSUE THREAD

**Issue by franchukpetro** [huggingface/optimum-benchmark#151]
Hi,

First of all, thank you for developing such a great tool for benchmarking models, that really helps during research.

I'm trying to run benchmarks for Mistral 7B float16 on RTX 4090 with 24GB of VRAM. However, I got CUDA out of memory for both current and previous [0.0.1 version](https://github.com/huggingface/optimum-benchmark/tree/0.0.1). I tried to benchmark Falcon1B just to check whether everything is working fine, and that worked for me.

Is there a way to reduce memory requirements for benchmarking Mistral 7B model on 24GB GPU card? Theoretically, float16 7B model should require 14-16GB of VRAM, so I don't really understand what consumes rest of the GPU memory during benchmarking.

Just in case, I was using your [original config file for Mistral7B](https://github.com/huggingface/optimum-benchmark/blob/0.0.1/examples/running-mistrals/configs/_base_.yaml), but seems like you were running it on A100 80GB.

**Comment by IlyasMoutawwakil** [comment]
Hi,
The theoretical requirement you calculated only count model weights (2 bytes per param * 7b param) but the activations take about the same amount of memory during inference. Try running this simple script:
```python
import torch
from transformers import AutoModelForCausalLM

model = AutoModelForCausalLM.from_pretrained("mistralai/Mistral-7B-v0.1").cuda(1)

input_ids = torch.randint(0, 1000, (2, 128)).cuda(1)

with torch.inference_mode():
    model.generate(input_ids, max_new_tokens=128)

print(torch.cuda.max_memory_allocated(1) / 1000**2, "MB")
print(torch.cuda.max_memory_reserved(1) / 1000**2, "MB")
```
which requires a minimum of 30GB of VRAM.

**Comment by andxalex** [comment]
Slightly modified the above script, but it returns 15GBs of VRAM:

```
import torch
from transformers import AutoModelForCausalLM

model = AutoModelForCausalLM.from_pretrained("mistralai/Mistral-7B-v0.1", 
                                            torch_dtype = torch.float16,).cuda("cuda:0")

input_ids = torch.randint(0, 1000, (2, 128)).cuda("cuda:0")

with torch.inference_mode():
    model.generate(input_ids, max_new_tokens=128)

print(torch.cuda.max_memory_allocated("cuda:0") / 1000**2, "MB")
print(torch.cuda.max_memory_reserved("cuda:0") / 1000**2, "MB")
```

![image](https://github.com/huggingface/optimum-benchmark/assets/146676764/570ff285-ef2e-4fb4-850d-e76690d715a0)

**Comment by IlyasMoutawwakil** [comment]
@andxalex thanks , I ran the same config @franchukpetro was referring to (without explicitly specifying the dtype).
I honestly thought, probably like @franchukpetro, that the `safetensors` dtype was used by default when dtype is not specified [(bf16 in this case)](https://huggingface.co/mistralai/Mistral-7B-v0.1?show_tensors=true), but it seems to not always be the case 🤔

**Comment by franchukpetro** [comment]
Thanks for the replies!

So I've just tried running benchmark with 0.0.1 version, with the next .yaml config file:

```yaml
defaults:
  - backend: pytorch # default backend
  - launcher: inline # default launcher
  - benchmark: inference # default benchmark
  - experiment # inheriting from experiment config
  - _self_ # for hydra 1.1 compatibility
  - override hydra/job_logging: colorlog # colorful logging
  - override hydra/hydra_logging: colorlog # colorful logging

hydra:
  run:
    dir: experiments/${experiment_name}
  sweep:
    dir: experiments/${experiment_name}
  job:
    chdir: true
    env_set:
      CUDA_VISIBLE_DEVICES: 0
      CUDA_DEVICE_ORDER: PCI_BUS_ID
  sweeper:
    params:
      benchmark.input_shapes.batch_size: 1,2,4,8,16

experiment_name: fp16-batch_size(${benchmark.input_shapes.batch_size})-sequence_length(${benchmark.input_shapes.sequence_length})-new_tokens(${benchmark.new_tokens})
model: mistralai/Mistral-7B-v0.1
device: cuda

backend:
  torch_dtype: float16

benchmark:
  memory: true
  warmup_runs: 10

  new_tokens: 1000
  input_shapes:
    sequence_length: 512

```

That is the same config file as provided in [this example](https://github.com/huggingface/optimum-benchmark/blob/0.0.1/examples/running-mistrals/configs/_base_.yaml), the only difference is addition of launcher, which was required to avoid errors.

As you can see, the dtype is specified to be float16, while I've also tried bfloat16 - both resulted in CUDA out of memory.

I'll try to do same benchmark now as @andxalex adviced, with Python API. 

Actually, the only reason why I'm doing benchmarking with older version is because I want to generate nice visualizations, with scripts like [report.py](https://github.com/huggingface/optimum-benchmark/blob/0.0.1/examples/running-mistrals/report.py), to get plots similar to [this tutorial](https://huggingface.co/docs/transformers/main/en/quantization#benchmarks). I'll probably try to combine Python API to get the benchmark data, and report.py file from previous version, but it would be great to have some kind of documentation about that @IlyasMoutawwakil in the new version.
