### ISSUE TITLE
Running the training benchmark with timm model produces error

### ISSUE THREAD

**Issue by aliabdelkader** [huggingface/optimum-benchmark#161]
I tried to run the training benchmark with a timm model. I got the following error
![image](https://github.com/huggingface/optimum-benchmark/assets/40035243/c3ca8d08-f8f4-4d86-98a8-4cf50be14848)

It seems that an `index out of range error` occurs trainer attempts to fetch a batch from the dataset using the data loader

*steps to reproduce:*
- create the following configuration file (`cpu_training_pytorch_timm`) in the tests/configs directory
```yaml
defaults:
  - backend: pytorch
  # order of inheritance, last one overrides previous ones
  - _base_ # inherits from base config
  - _training_ # inherits from training config
  - _timm_ # inherits from timm config
  - _cpu_ # inherits from cpu config
  - _self_ # hydra 1.1 compatibility

experiment_name: cpu_training_pytorch_timm

benchmark:
    training_arguments:
      use_cpu: true

 ```
- run the benchmark using pytest 
```bash
pytest -k "cpu_training_pytorch_timm"
```
or using cli
```bash
optimum-benchmark --config-dir tests/configs/ --config-name cpu_training_pytorch_timm.yaml
```

- Expected
benchmark runs successfully

- obtained
access out of bound error
