### ISSUE TITLE
Onnxruntime Seq2Seq doesn't work

### ISSUE THREAD

**Issue by Knzaytsev** [huggingface/optimum-benchmark#180]
It appears that when attempting to run a Seq2Seq model using the onnxruntime framework, an error arises after executing a config file in the command line. The error message indicates:
```
  File "/home/isolated-optimum-benchmark/optimum-benchmark/optimum_benchmark/benchmarks/inference/inputs_utils.py", line 18, in extract_text_generation_inputs
    raise ValueError("Could not find any valid text generation inputs.")
ValueError: Could not find any valid text generation inputs.
```

Additionally, in the logs, a warning regarding inputs is present:
```
[PROC-0][2024-04-12 15:21:38,250][benchmark][INFO] - Allocating inference benchmark
[PROC-0][2024-04-12 15:21:38,250][inference][INFO] -    + Creating input generator
[PROC-0][2024-04-12 15:21:38,250][input][INFO] -        + Using text2text-generation task generator
[PROC-0][2024-04-12 15:21:38,250][inference][INFO] -    + Generating Text Generation inputs
[PROC-0][2024-04-12 15:21:38,251][inference][INFO] -    + Preparing Text Generation inputs
[PROC-0][2024-04-12 15:21:38,251][onnxruntime][WARNING] - Input input_ids is not in expected inputs names. Removing it.
[PROC-0][2024-04-12 15:21:38,251][onnxruntime][WARNING] - Input decoder_input_ids is not in expected inputs names. Removing it.
[PROC-0][2024-04-12 15:21:38,251][onnxruntime][WARNING] - Input attention_mask is not in expected inputs names. Removing it.
[PROC-0][2024-04-12 15:21:38,251][onnxruntime][WARNING] - Input position_ids is not in expected inputs names. Removing it.
```

It seems that the issue may lie in the usage of input names in ORTModelForSeq2SeqLM. Specifically, in the inputs_names property within the onnxruntime backend, there is a check of attributes:
```
  @property
  def inputs_names(self) -> List[str]:
      if hasattr(self.pretrained_model, "inputs_names"):
          return self.pretrained_model.inputs_names
      elif hasattr(self.pretrained_model, "input_names"):
          return self.pretrained_model.input_names
      else:
          return []
 ```

However, ORTModelForSeq2SeqLM does not possess such attributes. The encoder and decoder of the pretrained model have "input_names".

For reference, here is the content of the config file:
```
defaults:
  - experiment # inheriting experiment schema
  - benchmark: inference
  - launcher: process
  - backend: onnxruntime
  - _self_ # for hydra 1.1 compatibility
  - override hydra/job_logging: colorlog # colorful logging
  - override hydra/hydra_logging: colorlog # colorful logging

experiment_name: pytorch_t5_small

launcher:
  device_isolation: true

benchmark:
  latency: true
  memory: true

backend:
  device: cpu
  no_weights: false
  use_io_binding: false
  model: google-t5/t5-small
  export: true
  library: transformers
  task: text2text-generation

# hydra/cli specific settings
hydra:
  run:
    # where to store run results
    dir: runs/${experiment_name}
  job:
    # change working directory to the run directory
    chdir: true
    env_set:
      # set environment variable OVERRIDE_BENCHMARKS to 1
      # to not skip benchmarks that have been run before
      OVERRIDE_BENCHMARKS: 1
```
