### ISSUE TITLE
hangs，can not continue.

### ISSUE THREAD

**Issue by gaogaoSpark** [huggingface/optimum-benchmark#189]
### pytorch_llama.yaml
```
defaults:
  - experiment # inheriting experiment schema
  - benchmark: inference
  - launcher: torchrun
  - backend: pytorch
  - _self_ # for hydra 1.1 compatibility
  - override hydra/job_logging: colorlog # colorful logging
  - override hydra/hydra_logging: colorlog # colorful logging

experiment_name: pytorch_llama

launcher:
  #device_isolation_action: warn
  device_isolation: true
  nproc_per_node: 4

backend:
  device: cuda
  device_ids: 0,1,2,3
  no_weights: true
  model: FlagAlpha/Llama2-Chinese-13b-Chat
  task: text-generation

benchmark:
  input_shapes:
    batch_size: 12
    sequence_length: 2048
  new_tokens: 256
```
### logs
![log](https://github.com/huggingface/optimum-benchmark/assets/16930471/f699a0d1-c771-4165-a66c-edf88635a804)
