### ISSUE TITLE
vllm backend uses too much vram

### ISSUE THREAD

**Issue by flyer103** [huggingface/optimum-benchmark#213]
For the `llama3-8b` model, using `pytorch` backend on `A30` can test normally, but when using `vllm` backend, `torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 48.00 MiB. GPU` exception will be reported.

Does vllm backend will use about 2x the model size?

Config file:
```yaml
defaults:
  - benchmark
  - scenario: inference
  - launcher: process
  - backend: vllm
  - _self_

name: vllm_llama3_8b_fp16

launcher:
  device_isolation: true
  device_isolation_action: warn

backend:
  device: cuda
  device_ids: 0
  no_weights: true
  dtype: float16
  task: text-generation
  library: transformers
  model: /rawmodels/llama3-8b/

scenario:
  iterations: 10
  duration: 10
  warmup_runs: 10
  latency: true
  memory: true
  input_shapes:
    batch_size: 1
    sequence_length: 256
  generate_kwargs:
    min_new_tokens: 100
    max_new_tokens: 100

hydra:
  run:
    dir: runs/${name}
  job:
    chdir: true
    env_set:
      OVERRIDE_BENCHMARKS: 1
```
