### ISSUE TITLE
Process isolation is not working on MPS device

### ISSUE THREAD

**Issue by baptistecolle** [huggingface/optimum-benchmark#230]
Setting up the launcher to `process` on an MPS device causes the benchmark to be stuck permanently on “Sending report to main process.”

Steps to reproduce:
Run this configuration on an MPS device (Mac M-series).
```
defaults:
  - benchmark
  - scenario: inference
  - **launcher: process # launcher: inline works**
  - backend: pytorch
  - _base_
  - _self_

name: pytorch_bert

scenario:
  latency: true
  memory: true
  input_shapes:
    batch_size: 1
    sequence_length: 128

backend:
  device: mps
  no_weights: true
  model: bert-base-uncased
```
(example adapted from `pytorch_bert.yaml`)

Temporary Solution: set to `launcher: inline`

Remarks: `launcher.start_method: fork` does not also work on mac
