### ISSUE TITLE
LLama-3.1-70B on 2x NVIDIA L40S results in ﻿﻿torch.cuda.OutOfMemoryError

### ISSUE THREAD

**Issue by j-irion** [huggingface/optimum-benchmark#241]
When I try to run LLama-3.1-70B on two NVIDIA L40S it results in a torch.cuda.OutOfMemoryError. I tried simultaniously watching the VRAM usage and saw that the first L40S is getting filled up and then the error occurs. Is this expected behaviour?

This is the config I am using:
```yaml
defaults:
  - benchmark
  - scenario: inference
  - launcher: process
  - backend: pytorch
  - _base_
  - _self_

name: pytorch_llama

launcher:
  device_isolation: true
  device_isolation_action: warn

backend:
  model: meta-llama/Meta-Llama-3.1-70B
  device: cuda
  device_ids: 0,1
  torch_dtype: float16

scenario:
  memory: true
  latency: true
  energy: true

  warmup_runs: 10
  iterations: 10
  duration: 10

  input_shapes:
    batch_size: 1
    sequence_length: 256
  generate_kwargs:
    max_new_tokens: 32
    min_new_tokens: 32
```
