### ISSUE TITLE
TensorRT-LLM pipeline parallelism is broken

### ISSUE THREAD

**Issue by asesorov** [huggingface/optimum-benchmark#259]
## Problem Description

When trying to use pipeline parallelism in tensorrt-llm on 2+ NVIDIA GPUs, I encounter ```AssertionError: Expected but not provided tensors:{'transformer.vocab_embedding.weight'}```. I tried other models, but error is the same.

## Environment

- GPUs: 2xNVIDIA RTX 4090
- Docker: optimum-nvidia (0.1.0b7, latest available)
- Optimum Benchmark version: 0.4.0

## Optimum Benchmark configuration
```
defaults:
  - benchmark
  - backend: tensorrt-llm
  - scenario: inference
  - launcher: process
  - _self_

name: trt_llama

launcher:
  device_isolation: true
  device_isolation_action: warn

backend:
  device: cuda
  dtype: bfloat16
  device_ids: 0,1
  max_prompt_length: 1024
  max_batch_size: 16
  max_new_tokens: 100
  tp: 1
  pp: 2
  world_size: 2
  gpus_per_node: 2
  model: IlyaGusev/saiga_llama3_8b

scenario:
  latency: true
  memory: false
  energy: false
  input_shapes:
    batch_size: 1
    sequence_length: 128
  generate_kwargs:
    max_new_tokens: 100
    min_new_tokens: 100
```

## Logs

With mpirun: 
[trt-llm_2gpus_pp_mpirun_n2.log](https://github.com/user-attachments/files/16976641/trt-llm_2gpus_pp_mpirun_n2.log)

Without mpirun: 
[trt-llm_2gpus_pp.log](https://github.com/user-attachments/files/16976643/trt-llm_2gpus_pp.log)

Preview of the error:
```
AssertionError: Expected but not provided tensors:{'transformer.vocab_embedding.weight'}
```

**Comment by IlyasMoutawwakil** [comment]
Hello, does this same configuration work for you outside of the context of `optimum-benchmark` ?
Also how did you launch your benchmarks ? You mentioned `mpirun` but I'm not sure that's needed to run distributed trt-llm.

**Comment by asesorov** [comment]
@IlyasMoutawwakil when running without mpi, I get `RuntimeError: [TensorRT-LLM][ERROR] Assertion failed: mpiSize == tp * pp (/src/tensorrt_llm/cpp/tensorrt_llm/runtime/worldConfig.cpp:90)`

Here's the configuration I use:
```
defaults:
  - benchmark
  - backend: tensorrt-llm
  - scenario: inference
  - launcher: process
  - _self_

name: trt_llama

launcher:
  device_isolation: true
  device_isolation_action: warn

backend:
  device: cuda
  dtype: bfloat16
  device_ids: 0,1
  max_prompt_length: 1024
  max_batch_size: 16
  tp: 2
  pp: 1
  world_size: 2
  gpus_per_node: 2
  model: TinyLlama/TinyLlama-1.1B-Chat-v1.0

scenario:
  latency: true
  memory: false
  energy: false
  input_shapes:
    batch_size: 1
    sequence_length: 128
  generate_kwargs:
    max_new_tokens: 100
    min_new_tokens: 100
```

And command line which successfully launches the benchmark: `mpirun -n 2 --allow-run-as-root optimum-benchmark --config-dir /mnt/host --config-name trt_llama_2gp us`. However, without mpi I'm getting the `mpiSize == tp * pp` assertion error. Please, tell me if I'm doing something wrong. Thank you in advance.
