### ISSUE TITLE
Error: Another instance of codecarbon is already running

### ISSUE THREAD

**Issue by j-irion** [huggingface/optimum-benchmark#260]
Hello, 
When I try to track the energy consumption with the benchmark, I get the following error:
`Error: Another instance of codecarbon is already running. Turn off the other instance to be able to run this one. Exiting.`

Afterwards I get another Error: 
`AttributeError: 'EmissionsTracker' object has no attribute '_scheduler'`

I noticed that, when I reboot the machine, the first run crashes later than the consequent runs and also saves to the task_codecarbon.json. Here are the logs of the first and second run:
[first_run_after_reboot.log](https://github.com/user-attachments/files/16982005/first_run_after_reboot.log)
[second_run.log](https://github.com/user-attachments/files/16982006/second_run.log)

I tried running the benchmark with the following config:

```yaml
defaults:
  - benchmark
  - scenario: inference
  - launcher: process
  - backend: pytorch
  - _base_
  - _self_

name: pytorch_llama_8b_energy

launcher:
  device_isolation: true
  device_isolation_action: warn

backend:
  model: meta-llama/Meta-Llama-3.1-8B
  device: cuda
  device_ids: 0,1
  device_map: auto
  torch_dtype: float16

scenario:
  memory: true
  latency: true
  energy: true

  warmup_runs: 10
  iterations: 10
  duration: 10

  input_shapes:
    batch_size: 2
    sequence_length: 512
  generate_kwargs:
    max_new_tokens: 32
    min_new_tokens: 32
```
