### ISSUE TITLE
CUDA_VISIBLE_DEVICES is not captured by torch

### ISSUE THREAD

**Issue by fxmarty** [huggingface/optimum-benchmark#27]
As per title.

For example setting

```
hydra:
  job:
    env_set:
      CUDA_VISIBLE_DEVICES: 4,5
```

does not work and the model will be loaded on devices 0, 1. I believe there's a bug somewhere in the trainer or transformers (or hydra, or torch) where things mess up when `CUDA_VISIBLE_DEVICES` is set after torch import.

Launching with `CUDA_VISIBLE_DEVICES=3,4 optimum-benchmark` solves the issue.

I think we should abandon the hydra/job/env_set approach, this just means that the CI should be edited accordingly.
