### ISSUE TITLE
fp16 inference with onnxruntime backend

### ISSUE THREAD

**Issue by shuyuelan** [huggingface/optimum-benchmark#7]
Hi,

I tried to run the bert example shown in readme for fp16 inference by changing https://github.com/huggingface/optimum-benchmark/blob/main/src/backend/onnxruntime.py#L78 to `fp16: True`, but the resulting throughput I got is similar to the false case. Is it expected or I should set fp16 somewhere else?

Here is the command I ran:
`python3 main.py --config-name bert backend=onnxruntime device=cuda`

Thanks.

**Comment by IlyasMoutawwakil** [comment]
There are multiple fp16 features, one of them is fp16 weights which is accessible during the torch->onnx through `backend.torch_dtype`. 
The other one is onnxruntime's `fp16` optimization which will downcast some ops (also referred to as mixed precision) https://onnxruntime.ai/docs/performance/model-optimizations/float16.html#mixed-precision
depending on the setting/model size/weights datatype you might or might not notice throughput improvements.
for example for small models, or if you're comparing to a model that's fully exported in float16.

**Comment by shuyuelan** [comment]
Thanks @IlyasMoutawwakil for the quick reply! Does the second way match the change I did in the description? For these two methods, are they  both effective on both onnxruntime and pytorch backend, or backend.torch_dtype for pytorch and the `fp16` setting for onnxruntime?

I am curious about the results shown on the leaderboard https://huggingface.co/spaces/optimum/llm-perf-leaderboard. For example for distilgpt2, how did we get the fp16 result for pytorch and onnxruntime? Did they use the `torch_dtype` setting or `fp16` setting in ORT optimization? It is very appreciated if you could share the commands to reproduce these results. Thanks.

**Comment by IlyasMoutawwakil** [comment]
Yes the second method corresponds to the change you made.
For pytorch you can use `backend.torch_dtype=float16` to downcast weights and/or `backend.amp_autocast=true` to downcast some ops (mixed precision).
Equivalently, for onnxruntime it's also `backend.torch_dtype=float16` (used during export) and/or `backend.optimization_config.fp16=true`.

For the llm-perf I'm using config templates like this one for oonnxruntime with float16 weights:

```yaml
defaults:
  - backend: onnxruntime # default backend
  - benchmark: inference # default benchmark
  - experiment # inheriting from experiment config
  - _self_ # for hydra 1.1 compatibility
  - override hydra/job_logging: colorlog # colorful logging
  - override hydra/hydra_logging: colorlog # colorful logging

hydra:
  run:
    dir: llm-experiments/{experiment_name}
  job:
    chdir: true

experiment_name: {experiment_name}

model: {model}
cache_kwargs:
  revision: {revision}
  use_auth_token: true
  trust_remote_code: true

device: cuda

backend:
  no_weights: true
  use_merged: true
  delete_cache: true
  torch_dtype: float16

benchmark:
  memory: true

  input_shapes:
    batch_size: 1
    sequence_length: 1

  new_tokens: 1000

```
The use of full float16 "downcasting" instead of mixed precision is justified by the fact that most of these models/LLMs are either pretrained in float16 or bfloat16 (which are generally computationally equivalent). Probably not the case for `distilgpt2` but for the big ones it's the case.
